import chalk from "chalk";
import { loadConfig, loadHistory, calculateQuota } from "./config.js";

export function generateReport(): string {
  const config = loadConfig();
  const history = loadHistory();
  const quota = calculateQuota(config);

  const burnPercent = quota.totalBudget > 0 ? (config.burnedCost / quota.totalBudget) * 100 : 0;
  const totalSessions = history.length;
  const totalTokens = history.reduce((sum, s) => sum + s.tokensUsed, 0);
  const totalCost = history.reduce((sum, s) => sum + s.costUsd, 0);
  const totalDuration = history.reduce((sum, s) => sum + s.duration, 0);

  const strategyCounts: Record<string, number> = {};
  const providerCounts: Record<string, number> = {};
  for (const session of history) {
    strategyCounts[session.strategy] = (strategyCounts[session.strategy] || 0) + 1;
    providerCounts[session.provider] = (providerCounts[session.provider] || 0) + 1;
  }

  const favoriteStrategy = Object.entries(strategyCounts).sort(
    (a, b) => b[1] - a[1],
  )[0];

  const now = new Date();
  const startDate = new Date(config.startDate);
  const daysSinceStart = Math.max(
    1,
    Math.floor((now.getTime() - startDate.getTime()) / (1000 * 60 * 60 * 24)),
  );
  const daysRemaining = Math.max(0, quota.periodDays - daysSinceStart);
  const projectedYearEnd =
    daysSinceStart > 0
      ? (totalCost / daysSinceStart) * quota.periodDays
      : 0;
  const projectedPercent =
    quota.totalBudget > 0 ? (projectedYearEnd / quota.totalBudget) * 100 : 0;

  const complianceGrade =
    burnPercent >= 50
      ? "A+"
      : burnPercent >= 40
        ? "A"
        : burnPercent >= 30
          ? "B"
          : burnPercent >= 20
            ? "C"
            : burnPercent >= 10
              ? "D"
              : "F";

  const lines = [
    chalk.bold.underline("TOKEN QUOTA COMPLIANCE REPORT"),
    chalk.gray(`Generated: ${now.toISOString()}`),
    chalk.gray(`Reporting Period: ${config.quotaPeriod} (started ${config.startDate})`),
    ``,
    chalk.bold("EMPLOYEE PROFILE"),
    `  Annual Compensation:  ${config.currency} ${config.salary.toLocaleString()}`,
    `  Token Budget (50%):   ${config.currency} ${quota.totalBudget.toLocaleString()}`,
    `  Daily Target:         ${config.currency} ${quota.dailyTarget.toFixed(2)}`,
    ``,
    chalk.bold("CONSUMPTION METRICS"),
    `  Total Sessions:       ${totalSessions}`,
    `  Total Tokens Burned:  ${totalTokens.toLocaleString()}`,
    `  Total Cost Incurred:  $${totalCost.toFixed(4)}`,
    `  Total Burn Time:      ${(totalDuration / 1000 / 60).toFixed(1)} minutes`,
    `  Avg Cost/Session:     $${totalSessions > 0 ? (totalCost / totalSessions).toFixed(4) : "0.0000"}`,
    ``,
    chalk.bold("COMPLIANCE STATUS"),
    `  Current Burn Rate:    ${burnPercent.toFixed(4)}%`,
    `  Projected Year-End:   ${projectedPercent.toFixed(2)}%`,
    `  Compliance Grade:     ${complianceGrade}`,
    `  Days Remaining:       ${daysRemaining}`,
    `  Shortfall:            $${Math.max(0, quota.totalBudget - totalCost).toFixed(2)}`,
    ``,
    chalk.bold("STRATEGY BREAKDOWN"),
    ...Object.entries(strategyCounts).map(
      ([s, c]) => `  ${s.padEnd(15)} ${c} sessions`,
    ),
    `  Preferred Strategy:   ${favoriteStrategy ? favoriteStrategy[0] : "none"}`,
    ``,
    chalk.bold("PROVIDER BREAKDOWN"),
    ...Object.entries(providerCounts).map(
      ([p, c]) => `  ${p.padEnd(15)} ${c} sessions`,
    ),
    ``,
    chalk.bold("RECOMMENDATION"),
    getRec(burnPercent, daysRemaining, quota.dailyTarget, totalCost, daysSinceStart),
    ``,
    chalk.gray("---"),
    chalk.gray("This report was generated by TokenBurn v1.0.0"),
    chalk.gray("Inspired by Jensen Huang, GTC 2026"),
    chalk.gray('"If that $500,000 engineer did not consume at least'),
    chalk.gray('$250,000 worth of tokens, I am going to be deeply alarmed."'),
  ];

  return lines.join("\n");
}

function getRec(
  burnPercent: number,
  daysRemaining: number,
  dailyTarget: number,
  totalCost: number,
  daysSinceStart: number,
): string {
  if (burnPercent >= 50) {
    return chalk.green(
      "  Congratulations! You have achieved exemplary compliance.\n" +
        "  Jensen Huang would personally shake your hand.\n" +
        "  Consider mentoring colleagues who are struggling with their quotas.",
    );
  }
  if (burnPercent >= 25) {
    return chalk.yellow(
      "  Your burn rate is below optimal levels.\n" +
        `  You need to increase daily burn to $${((dailyTarget * (daysSinceStart + daysRemaining) - totalCost) / Math.max(1, daysRemaining)).toFixed(2)}/day.\n` +
        "  Consider switching to 'emergency' mode or the 'inception' strategy\n" +
        "  for maximum token throughput.",
    );
  }
  return chalk.red(
    "  CRITICAL: Your token consumption is dangerously low.\n" +
      "  Jensen Huang is deeply alarmed.\n" +
      "  Immediate action required: activate emergency mode with --emergency.\n" +
      "  Schedule daily burn sessions. Your career may depend on it.",
  );
}
